name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [8.0, 8.1]
        laravel_version: [9.*]

    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}

      - name: Validate composer.json
        run: composer validate

      - name: Run composer install
        run: composer install --no-interaction --no-suggest

      - name: Run find-and-replace to replace * with 0
        uses: mad9000/actions-find-and-replace-string@1
        id: laravel_version_cleaned
        with:
          source: ${{ matrix.laravel_version }}
          find: '*'
          replace: '0'

      - name: Install Laravel
        run: composer update --no-interaction illuminate/database:^${{ steps.laravel_version_cleaned.outputs.value }}

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit
